### ISSUE TITLE
Implementations of deleteFindMin and deleteFindMax are wrong

### ISSUE THREAD

**Issue by bos** [haskell/critbit#15]
I applied #8 even though it had a couple of bugs, because I hope that @archblob will have a good time fixing the bug.

See ae06352de003baea81f9f8f9b41d5705925b4d77 for new tests that are simpler than the originals and that correctly expose the bugs.

**Comment by r-vdp** [comment]
I think this issue may be closed now?

**Comment by bos** [comment]
Yes, thanks for the reminder.
