### ISSUE TITLE
alter is slower than its counterpart in containers

### ISSUE THREAD

**Issue by bos** [haskell/critbit#35]
As reported by criterion.

critbit:

```
benchmarking bytestring/alter/critbit
mean: 587.6628 ns
std dev: 25.92060 ns
```

map:

```
benchmarking bytestring/alter/map
mean: 481.7831 ns
std dev: 13.77285 ns
```

Hoping that @archblob can take a look.

**Comment by archblob** [comment]
I will take a look this afternoon.

**Comment by archblob** [comment]
I have rewritten alter without using continuations and it is now within 10ns of the containers equivalent. Also, I profiled the function for time and space to see if I can find something, but if it is there I missed it.
I will be looking at the Core later tonight but my knowledge of what to look for is very limited, I will see what I can find and amend my commit.

**Comment by bos** [comment]
Looks like you did a good job of fixing it.

```
benchmarking bytestring/alter/critbit
mean: 419.6718 ns
std dev: 13.98493 ns
```

Thanks!
